version: 2

references:
  terraform-image: &terraform-image
    docker:
      - image: hashicorp/terraform:0.11.10 

jobs:
  terraform-plan:
    <<: *terraform-image
    steps:
      - checkout
      - run: terraform init
      - run: terraform fmt -check || exit 1
      - run: terraform plan
  terraform-apply:
    <<: *terraform-image
    steps:
      - checkout
      - run: terraform init
      - run: terraform apply -auto-approve

workflows:
  version: 2
  build-deploy:
    jobs:
      - terraform-plan:
          filters:
            branches:
              ignore: master
      - terraform-apply:
          filters:
            branches:
              only: master  
 